Add bin scripts

diff --git a/scripts/pull-all b/scripts/pull-all
--- a/scripts/pull-all
+++ b/scripts/pull-all
@@ -1,36 +1,45 @@
 #!/bin/bash
+#
+# Update all nested directories in current directory to main
+. _utils
 
 
-RED='\033[0;31m'
-GREEN='\033[0;32m'
-YELLOW='\033[1;33m'
-NC='\033[0m'
+#######################################
+# Update all nested directories in current directory to main
+# Arguments:
+#   None
+# Outputs:
+#   None
+#######################################
+function run() {
+    for repo in basename "$PWD"
+    do
+        if [[ ! -d $repo/.git ]]
+        then
+            continue
+        fi
 
-for repo in basename "$PWD"
-do
-    if [[ ! -d $repo/.git ]]
-    then
-        continue
-    fi
+        cd $repo
+        repoName=$(basename $repo)
+        branch=$(git symbolic-ref --short HEAD)
 
-    cd $repo
-    repoName=$(basename $repo)
-    branch=$(git symbolic-ref --short HEAD)
+        if [[ $branch == "main" ]]
+        then
+            echo -n "Updating $repoName... "
+            git pull origin main > /dev/null 2>&1
+            RESULT=$?
 
-    if [[ $branch == "main" ]]
-    then
-        echo -n "Updating $repoName... "
-        git pull origin main > /dev/null 2>&1
-        RESULT=$?
+        if [ $RESULT -eq 0 ]
+        then
+            echo -e "${GREEN}DONE${NC}"
+        else
+            echo -e "${RED}FAILED!!!${NC}"
+        fi
+        else
+        echo -e "${YELLOW}Skipping $repoName on branch $branch${NC}"
+        fi
 
-    if [ $RESULT -eq 0 ]
-    then
-        echo -e "${GREEN}DONE${NC}"
-    else
-        echo -e "${RED}FAILED!!!${NC}"
-    fi
-    else
-    echo -e "${YELLOW}Skipping $repoName on branch $branch${NC}"
-    fi
+    done
+}
 
-done
+run
